name: semver
version: 0.2.1
author: Guillermo López-Anglada <guillermo.lopez@outlook.com>
description: A 'parser' for valid semantic version tags.
homepage: https://github.com/guillermooo/dart-semver
dependencies:
  string_scanner: ">=0.1.3 <1.0.0"
dev_dependencies:
  unittest: ">=0.11.0+2 <0.12.0"
